/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Aplicacion_de_Gestion.*;
import Comparadores.CriterioCalendario;
import Interfaz.Renderers.ColorRenderer;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class Frame_Principal extends javax.swing.JFrame {

    ArrayList<Calendario> datosCalendario;
    int semanaActualVista;
    /**
     * Creates new form Frame_Principal
     */
    public Frame_Principal() {
        this.semanaActualVista = 1;
        this.datosCalendario =  new ArrayList<>();
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Gestión Empresa");
        this.RefreshTableEmpleadoData();
        this.datosCalendario = Gestion_Empresa.getInstance().Generar_Calendario_ArrayList(this.semanaActualVista);
        this.RefreshTableCalendarData();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_Horarios = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel_weekNumber = new javax.swing.JLabel();
        jComboBox_WeekPciker = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton_manualmente = new javax.swing.JButton();
        jButton_automaticamente = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_calendarios1 = new javax.swing.JTable();
        jButton_refreshHorarios = new javax.swing.JButton();
        jButton_refreshHorariosCurrentWeek = new javax.swing.JButton();
        jButton_closeWeek = new javax.swing.JButton();
        jPanel_Empleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleado = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelVacaciones = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelc32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelc24 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelc40 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNombreSeleccionado = new javax.swing.JLabel();
        jLabelNombreSeleccionadoDNI = new javax.swing.JLabel();
        jLabelNombreSeleccionadoApellido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton_refreshEmpleados = new javax.swing.JButton();
        jButton_addEmployee = new javax.swing.JButton();
        jButton_fireEmployee = new javax.swing.JButton();
        jButton_bookVacations = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCambios = new javax.swing.JTable();
        jPanel_Informes = new javax.swing.JPanel();
        jPanel_Gestiones = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("<< Anterior");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Semana #");

        jLabel_weekNumber.setText("1");

        jComboBox_WeekPciker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton3.setText("Siguiente >>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );

        jButton_manualmente.setText("Manualmente");
        jButton_manualmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_manualmenteActionPerformed(evt);
            }
        });

        jButton_automaticamente.setText("Automáticamente");
        jButton_automaticamente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_automaticamenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_weekNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_WeekPciker, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_manualmente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_automaticamente)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel_weekNumber)
                    .addComponent(jComboBox_WeekPciker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_automaticamente)
                    .addComponent(jButton_manualmente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(395, Short.MAX_VALUE))
        );

        jLabel_weekNumber.getAccessibleContext().setAccessibleName("1");

        jTable_calendarios1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_calendarios1.setColumnSelectionAllowed(true);
        jTable_calendarios1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable_calendarios1.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable_calendarios1);
        jTable_calendarios1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jButton_refreshHorarios.setText("Actualizar Tabla ");
        jButton_refreshHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshHorariosActionPerformed(evt);
            }
        });

        jButton_refreshHorariosCurrentWeek.setText("Ver Semana Actual");
        jButton_refreshHorariosCurrentWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshHorariosCurrentWeekActionPerformed(evt);
            }
        });

        jButton_closeWeek.setText("Finalizar Semana Actual");
        jButton_closeWeek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_closeWeekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_HorariosLayout = new javax.swing.GroupLayout(jPanel_Horarios);
        jPanel_Horarios.setLayout(jPanel_HorariosLayout);
        jPanel_HorariosLayout.setHorizontalGroup(
            jPanel_HorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HorariosLayout.createSequentialGroup()
                .addGroup(jPanel_HorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_HorariosLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_HorariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton_refreshHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_refreshHorariosCurrentWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_closeWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel_HorariosLayout.setVerticalGroup(
            jPanel_HorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_HorariosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel_HorariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_refreshHorarios)
                    .addComponent(jButton_refreshHorariosCurrentWeek)
                    .addComponent(jButton_closeWeek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel_HorariosLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Horarios", jPanel_Horarios);

        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Estado", "Código ", "DNI", "Nombre", "Apellido", "Telefono", "Fecha nacimiento", "Banco de cuenta", "Número de cuenta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpleado.getTableHeader().setReorderingAllowed(false);
        jTableEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpleado);
        if (jTableEmpleado.getColumnModel().getColumnCount() > 0) {
            jTableEmpleado.getColumnModel().getColumn(0).setResizable(false);
            jTableEmpleado.getColumnModel().getColumn(1).setResizable(false);
            jTableEmpleado.getColumnModel().getColumn(2).setResizable(false);
            jTableEmpleado.getColumnModel().getColumn(3).setResizable(false);
            jTableEmpleado.getColumnModel().getColumn(4).setResizable(false);
            jTableEmpleado.getColumnModel().getColumn(5).setResizable(false);
            jTableEmpleado.getColumnModel().getColumn(6).setResizable(false);
            jTableEmpleado.getColumnModel().getColumn(7).setResizable(false);
            jTableEmpleado.getColumnModel().getColumn(8).setResizable(false);
        }

        jLabel2.setText("Cantidad contratos vacaciones:");

        jLabelVacaciones.setText("0");

        jLabel4.setText("Cantidad contratos  32 horas:");

        jLabelc32.setText("0");

        jLabel6.setText("Cantidad contratos 24 horas:");

        jLabelc24.setText("0");

        jLabel8.setText("Cantidad contratos  40 horas:");

        jLabelc40.setText("0");

        jLabel1.setText("Empleado seleccionado");

        jLabelNombreSeleccionado.setText("Nombre");

        jLabelNombreSeleccionadoDNI.setText("DNI");

        jLabelNombreSeleccionadoApellido.setText("Apellido");

        jLabel5.setText("DNI:");

        jLabel7.setText("Nombre: ");

        jLabel9.setText("Apellido: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNombreSeleccionadoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombreSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombreSeleccionadoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelVacaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelc24, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelc32, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelc40, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabelNombreSeleccionadoDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelNombreSeleccionado)
                    .addComponent(jLabel9)
                    .addComponent(jLabelNombreSeleccionadoApellido))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVacaciones)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelc24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelc40)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelc32))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButton_refreshEmpleados.setText("Actualizar Tabla ");
        jButton_refreshEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshEmpleadosActionPerformed(evt);
            }
        });

        jButton_addEmployee.setText("Agregar Empleado");
        jButton_addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addEmployeeActionPerformed(evt);
            }
        });

        jButton_fireEmployee.setText("Dar de Bajar/Alta Empleado");
        jButton_fireEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_fireEmployeeActionPerformed(evt);
            }
        });

        jButton_bookVacations.setText("Gestionar Vacaciones");
        jButton_bookVacations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_bookVacationsActionPerformed(evt);
            }
        });

        jTableCambios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha de cambio", "Descripción", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCambiosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCambios);

        javax.swing.GroupLayout jPanel_EmpleadosLayout = new javax.swing.GroupLayout(jPanel_Empleados);
        jPanel_Empleados.setLayout(jPanel_EmpleadosLayout);
        jPanel_EmpleadosLayout.setHorizontalGroup(
            jPanel_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_EmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_EmpleadosLayout.createSequentialGroup()
                        .addComponent(jButton_refreshEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_fireEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_bookVacations, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 470, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel_EmpleadosLayout.setVerticalGroup(
            jPanel_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_EmpleadosLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel_EmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_refreshEmpleados)
                    .addComponent(jButton_addEmployee)
                    .addComponent(jButton_fireEmployee)
                    .addComponent(jButton_bookVacations))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleados", jPanel_Empleados);

        javax.swing.GroupLayout jPanel_InformesLayout = new javax.swing.GroupLayout(jPanel_Informes);
        jPanel_Informes.setLayout(jPanel_InformesLayout);
        jPanel_InformesLayout.setHorizontalGroup(
            jPanel_InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
        );
        jPanel_InformesLayout.setVerticalGroup(
            jPanel_InformesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Informes", jPanel_Informes);

        javax.swing.GroupLayout jPanel_GestionesLayout = new javax.swing.GroupLayout(jPanel_Gestiones);
        jPanel_Gestiones.setLayout(jPanel_GestionesLayout);
        jPanel_GestionesLayout.setHorizontalGroup(
            jPanel_GestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
        );
        jPanel_GestionesLayout.setVerticalGroup(
            jPanel_GestionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gestiones", jPanel_Gestiones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_refreshEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshEmpleadosActionPerformed
        // TODO add your handling code here:
        this.RefreshTableEmpleadoData();
        
    }//GEN-LAST:event_jButton_refreshEmpleadosActionPerformed

    private void jTableEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpleadoMouseClicked
        // TODO add your handling code here:
        int indexselected = jTableEmpleado.getSelectedRow();
        Empleado e =  Gestion_Empresa.getInstance().getEmpleados().get(indexselected);
        this.jLabelVacaciones.setText(String.valueOf(e.getHistorial_empleado().getCant_contrato_vacaciones()));
        this.jLabelc24.setText(String.valueOf(e.getHistorial_empleado().getCant_contrato_24h()));
        this.jLabelc32.setText(String.valueOf(e.getHistorial_empleado().getCant_contrato_32h()));
        this.jLabelc40.setText(String.valueOf(e.getHistorial_empleado().getCant_contrato_40h()));
        this.jLabelNombreSeleccionadoDNI.setText(e.getDni());
        this.jLabelNombreSeleccionado.setText(e.getNombre());
        this.jLabelNombreSeleccionadoApellido.setText(e.getApellido());
        
        this.RefreshTableHistorialCambioEmpleadoData(e.getHistorial_cambios_empleado());
    }//GEN-LAST:event_jTableEmpleadoMouseClicked

    private void jTableCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCambiosMouseClicked
        // TODO add your handling code here:    
        
        
        
        
    }//GEN-LAST:event_jTableCambiosMouseClicked

    private void jButton_manualmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_manualmenteActionPerformed
        
        if(Gestion_Empresa.getInstance().getEmpleados().size()>4)
            new jFrame_CalendarStyleyPicker(this.semanaActualVista).setVisible(true);
        else
            JOptionPane.showMessageDialog(null, "No hay empleados activos suficientes para generar los turnos. \nPosiblemente alguien esté de vacaciones esa semana o haya que contratar más empleados","Turnos no generados",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton_manualmenteActionPerformed

    private void jButton_automaticamenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_automaticamenteActionPerformed
        int ContractNumber = 0;
        
        if(this.datosCalendario.size()==21) ///No es necesario generar el calendario!
            return;
        
        HashMap<Integer, Integer> NumContrato_Codigoempleados = new HashMap<>();
        for(Empleado e: Gestion_Empresa.getInstance().getEmpleados())
        {
            if(e.getestado_empleado() && !(e.getContrato(semanaActualVista) instanceof Contrato_Vacaciones)) //Empleado activo y no tiene vacaciones esta semana
            {
                NumContrato_Codigoempleados.put(ContractNumber, e.getCod_empleado());
                ContractNumber++;
                if(ContractNumber == 6)
                    break;        
            }
        }
        switch (ContractNumber) {
            case 5 -> Gestion_Empresa.getInstance().Asignar_Contratos_Automaticamente(NumContrato_Codigoempleados,semanaActualVista,3); ///3 es la opcion de 5 empleados
            case 6 -> Gestion_Empresa.getInstance().Asignar_Contratos_Automaticamente(NumContrato_Codigoempleados,semanaActualVista,0);
            default -> {
                JOptionPane.showMessageDialog(null, "No hay empleados activos suficientes para generar los turnos. \nPosiblemente alguien esté de vacaciones esa semana o haya que contratar más empleados","Turnos no generados",JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }
        
        this.datosCalendario = Gestion_Empresa.getInstance().Generar_Calendario_ArrayList(this.semanaActualVista);
        RefreshTableCalendarData();
        
        
    }//GEN-LAST:event_jButton_automaticamenteActionPerformed

    private void jButton_addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addEmployeeActionPerformed
        new JFrame_AltaEmpleado().setVisible(true);        
    }//GEN-LAST:event_jButton_addEmployeeActionPerformed

    private void jButton_fireEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_fireEmployeeActionPerformed
        int index =this.jTableEmpleado.getSelectedRow();
        if( index == -1)
        {
            JOptionPane.showMessageDialog(null, "Elige un empleado primero");
            return;
        }
        Empleado e = Gestion_Empresa.getInstance().getEmpleados().get(index);
        e.setestado_empleado( !e.getestado_empleado());
        
        e.AgregarComentarioHistorial(e.getestado_empleado() ? "Alta empleado": "Baja Empleado", true);
        
        RefreshTableEmpleadoData();
        this.jTableEmpleado.setRowSelectionInterval(index, index);
        RefreshTableHistorialCambioEmpleadoData(e.getHistorial_cambios_empleado());
        
        JOptionPane.showMessageDialog(null, "Este cambio no afecta a los contratos anteriores, solo a los posteriores");
        
        
    }//GEN-LAST:event_jButton_fireEmployeeActionPerformed

    private void jButton_bookVacationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_bookVacationsActionPerformed
        new JFrame_GestionVacaciones().setVisible(true);
    }//GEN-LAST:event_jButton_bookVacationsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.semanaActualVista++;
        this.jLabel_weekNumber.setText(String.valueOf(this.semanaActualVista));
        this.datosCalendario = Gestion_Empresa.getInstance().Generar_Calendario_ArrayList(this.semanaActualVista);
        RefreshTableCalendarData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(this.semanaActualVista>1)
        {
            this.semanaActualVista--;
            this.jLabel_weekNumber.setText(String.valueOf(this.semanaActualVista));
            this.datosCalendario = Gestion_Empresa.getInstance().Generar_Calendario_ArrayList(this.semanaActualVista);
            RefreshTableCalendarData();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_refreshHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshHorariosActionPerformed
        this.jLabel_weekNumber.setText(String.valueOf(this.semanaActualVista));
        this.datosCalendario = Gestion_Empresa.getInstance().Generar_Calendario_ArrayList(this.semanaActualVista);
        RefreshTableCalendarData();        
    }//GEN-LAST:event_jButton_refreshHorariosActionPerformed

    private void jButton_refreshHorariosCurrentWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshHorariosCurrentWeekActionPerformed
         // TODO add your handling code here:
         this.semanaActualVista = Gestion_Empresa.getInstance().getSemana_actual();
         this.jLabel_weekNumber.setText(String.valueOf(this.semanaActualVista));
         this.datosCalendario = Gestion_Empresa.getInstance().Generar_Calendario_ArrayList(semanaActualVista);
         RefreshTableCalendarData();
    }//GEN-LAST:event_jButton_refreshHorariosCurrentWeekActionPerformed

    private void jButton_closeWeekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_closeWeekActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton_closeWeekActionPerformed
    
    
    
    public void RefreshTableCalendarData()
    {
        DefaultTableModel model = (DefaultTableModel)this.jTable_calendarios1.getModel();
        for(int i=0;i<model.getRowCount();)
            model.removeRow(0);
        
        int counter=0;
        if(this.datosCalendario.size()==21)
        {   
            this.jButton_automaticamente.setEnabled(false);
            this.jButton_manualmente.setEnabled(false);
            for(int i=0;i<3;i++)
            {
                Object rowData[]= new Object[7];
                for(int j=0;j<7;j++)
                {
                    rowData[j] = this.datosCalendario.get(counter++).getCod_empleado();
                }
                model.addRow(rowData);
            }
        }
        else
        {
            this.jButton_automaticamente.setEnabled(true);
            this.jButton_manualmente.setEnabled(true);
        }
    }

    public void RefreshTableHistorialCambioEmpleadoData(ArrayList<Historial_Cambios> historiales) {
        DefaultTableModel model  = (DefaultTableModel) jTableCambios.getModel();
        for(int i=0;i<model.getRowCount();)
            model.removeRow(0);
        
        Object rowData[] = new Object[3];
        for (Historial_Cambios hc: historiales) { 
            rowData[0] = hc.getFecha_cambio(); 
            rowData[1] = hc.getDescripcion();
            rowData[2] = hc.getEstado(); 
            
            model.addRow(rowData);
        }
    }
    
    public void RefreshTableEmpleadoData() {
        DefaultTableModel model  = (DefaultTableModel) jTableEmpleado.getModel();
        for(int i=0;i<model.getRowCount();)
            model.removeRow(0);
        
        Object rowData[] = new Object[9];
        for (Empleado e: Gestion_Empresa.getInstance().getEmpleados()) {
            rowData[0] = e.getestado_empleado() ? "Activo" : "Despedido";
            rowData[1] = e.getCod_empleado();
            rowData[2] = e.getDni();
            rowData[3] = e.getNombre();
            rowData[4] = e.getApellido();
            rowData[5] = e.getTelefono();
            rowData[6] = e.getFecha_nacimiento();
            rowData[7] = e.getBanco_cuenta();
            rowData[8] = e.getNum_cuenta();
            
            model.addRow(rowData);
        }
        
        
        
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Principal principal = new Principal(); //Inicializar datos
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                new Frame_Principal().setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_addEmployee;
    private javax.swing.JButton jButton_automaticamente;
    private javax.swing.JButton jButton_bookVacations;
    private javax.swing.JButton jButton_closeWeek;
    private javax.swing.JButton jButton_fireEmployee;
    private javax.swing.JButton jButton_manualmente;
    private javax.swing.JButton jButton_refreshEmpleados;
    private javax.swing.JButton jButton_refreshHorarios;
    private javax.swing.JButton jButton_refreshHorariosCurrentWeek;
    private javax.swing.JComboBox<String> jComboBox_WeekPciker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNombreSeleccionado;
    private javax.swing.JLabel jLabelNombreSeleccionadoApellido;
    private javax.swing.JLabel jLabelNombreSeleccionadoDNI;
    private javax.swing.JLabel jLabelVacaciones;
    public javax.swing.JLabel jLabel_weekNumber;
    private javax.swing.JLabel jLabelc24;
    private javax.swing.JLabel jLabelc32;
    private javax.swing.JLabel jLabelc40;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel_Empleados;
    private javax.swing.JPanel jPanel_Gestiones;
    private javax.swing.JPanel jPanel_Horarios;
    private javax.swing.JPanel jPanel_Informes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTableCambios;
    private javax.swing.JTable jTableEmpleado;
    private javax.swing.JTable jTable_calendarios1;
    // End of variables declaration//GEN-END:variables
}
