/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Aplicacion_de_Gestion.Calendario;
import Aplicacion_de_Gestion.Turno;
import Aplicacion_de_Gestion.tipo_turno;
import Comparadores.CriterioCalendario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ronald
 */
public class JPanel_WeeklyCalendar extends javax.swing.JPanel {

    /**
     * Creates new form JPanel_WeeklyCalendar
     */
    
    ArrayList<Calendario> datos;
    
    public JPanel_WeeklyCalendar(ArrayList<Calendario> datos) {
        initComponents();
        this.datos = datos;
        
        this.datos.sort(new CriterioCalendario());
        RefreshTableCalendarData();
        
    }
    
    public void RefreshTableCalendarData()
    {
        DefaultTableModel model = (DefaultTableModel)this.jTable_calendarios.getModel();
        int counter=0;
        for(int i=0;i<3;i++)
        {
            Object rowData[]= new Object[7];
            for(int j=0;j<7;j++)
            {
                rowData[j] = this.datos.get(counter++);
            }
            model.addRow(rowData);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_calendarios = new javax.swing.JTable();

        jTable_calendarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_calendarios.setColumnSelectionAllowed(true);
        jTable_calendarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_calendarios);
        jTable_calendarios.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (jTable_calendarios.getColumnModel().getColumnCount() > 0) {
            jTable_calendarios.getColumnModel().getColumn(0).setResizable(false);
            jTable_calendarios.getColumnModel().getColumn(1).setResizable(false);
            jTable_calendarios.getColumnModel().getColumn(2).setResizable(false);
            jTable_calendarios.getColumnModel().getColumn(3).setResizable(false);
            jTable_calendarios.getColumnModel().getColumn(4).setResizable(false);
            jTable_calendarios.getColumnModel().getColumn(5).setResizable(false);
            jTable_calendarios.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_calendarios;
    // End of variables declaration//GEN-END:variables
}
